sudo: required
dist: trusty
language: cpp

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y liboce-*

compiler:
        - gcc

before_script:
        - mkdir build
        - cd build
        - cmake ..

script: make && make test
       
